### ISSUE TITLE
Docker 镜像bitnami/phabricator适用吗？

### ISSUE THREAD

**Issue by h77626592** [arielyang/phabricator_zh_Hans#13]
https://hub.docker.com/r/bitnami/phabricator    docker镜像 bitnami/phabricator  不适用吗 ？ 
我汉化后使用 右上角的 搜索出现问题
bitnami/phabricator
![图片](https://user-images.githubusercontent.com/53549152/104150395-b6547700-5414-11eb-9b92-0b76c4430c4d.png)

**Comment by h77626592** [comment]
未处理的异常（“PhutilAggregateException”）
所有配置的全文搜索服务都失败了。
    - Exception: DateTime::__construct(): Failed to parse time string (2021-01-11 12:00 上午) at position 17 (�): Unexpected character

**Comment by arielyang** [comment]
试着删除掉：
'AM' => '上午'
'am' => '上午'
两行

**Comment by arielyang** [comment]
> 试着删除掉：
> 'AM' => '上午'
> 'am' => '上午'
> 两行

在 PhabricatorSimplifiedChineseTranslation.php 文件中

**Comment by h77626592** [comment]
PhabricatorSimplifiedChineseTranslation.php 文件中没有

**Comment by arielyang** [comment]
> PhabricatorSimplifiedChineseTranslation.php 文件中没有

有的呀，你的文件是什么版本？

看最新的：https://raw.githubusercontent.com/arielyang/phabricator_zh_Hans/master/dist/(stable)%20Promote%202020%20Week%2037/PhabricatorSimplifiedChineseTranslation.php

**Comment by h77626592** [comment]
![图片](https://user-images.githubusercontent.com/53549152/105657313-0e07dd80-5eff-11eb-8698-be329f02a24b.png)
这个报错呢。。刚才PhabricatorSimplifiedChineseTranslation.php复制错了

**Comment by h77626592** [comment]
搜索  -> 高级搜索  功能 搜索时报
 
T4: 系统语言为中文时 搜索栏报错
        Maniphest 任务·已关闭

**Comment by h77626592** [comment]
使用 (stable) Promote 2020 Week 37 版本暂时已正常，多谢
