### ISSUE TITLE
出现错误！没有跑起来

### ISSUE THREAD

**Issue by heguangzhi** [arielyang/phabricator_zh_Hans#2]
info it worked if it ends with ok
1 verbose cli [ 'node', '/usr/local/bin/npm', 'start' ]
2 info using npm@3.1.2
3 info using node@v0.12.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart phabricator_zh_Hans@1.0.0
6 info start phabricator_zh_Hans@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info phabricator_zh_Hans@1.0.0 Failed to exec start script
9 verbose stack Error: phabricator_zh_Hans@1.0.0 start: `node index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:223:16)
9 verbose stack     at EventEmitter.emit (events.js:110:17)
9 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at ChildProcess.emit (events.js:110:17)
9 verbose stack     at maybeClose (child_process.js:1015:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (child_process.js:1087:5)
10 verbose pkgid phabricator_zh_Hans@1.0.0
11 verbose cwd /Users/guangzhihe/Work/phabricator_zh_Hans
12 error Darwin 17.5.0
13 error argv "node" "/usr/local/bin/npm" "start"
14 error node v0.12.7
15 error npm  v3.1.2
16 error code ELIFECYCLE
17 error phabricator_zh_Hans@1.0.0 start: `node index.js`
17 error Exit status 1
18 error Failed at the phabricator_zh_Hans@1.0.0 start script 'node index.js'.
18 error This is most likely a problem with the phabricator_zh_Hans package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:

**Comment by arielyang** [comment]
node@v0.12.7 is toooold
