### ISSUE TITLE
hi，我遇到了由于把AM,PM翻译为上午，下午，在首页搜索的地方报错

### ISSUE THREAD

**Issue by heguangzhi** [arielyang/phabricator_zh_Hans#3]
如下图：
![image](https://user-images.githubusercontent.com/21078070/57447144-e71bfa80-7288-11e9-92c9-da5093452202.png)

不知道翻译文件在哪里设置的AM 翻译为 ”下午“，通过检索，我没有检索到。谢谢了

**Comment by arielyang** [comment]
最新版本的翻译已经去掉了 AM/PM，所以使用最新版的翻译文件应该不会遇到这个问题。
